AWSTemplateFormatVersion: 2010-09-09
Description: Gtuc infrustracture on aws 

#Parameters:
Parameters:
    ec2InstanceTypes:
        Type: String 
        Description: Select on instance
        Default: micro 
        AllowedValues:
            - micro 
            - small 
            - medium 
#Mappings
Mappings:
    ec2InstanceTypeImapping:
        micro:
            instanceType: t2.micro 
        small:
            instanceType: t2.small 
        medium:
            instanceType: t2.medium
#Conditions 
Conditions:
    whenEnvironmentEqualsMicro: !Equals [ec2InstanceTypes, micro]
